language: python
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=django19-py27
  - TOXENV=django19-py3
  - TOXENV=django110-py27
  - TOXENV=django110-py3
  - TOXENV=django111-py27
  - TOXENV=django111-py3
